# Generated by Django 5.1.5 on 2025-01-24 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.client'),
        ),
    ]
