# Generated by Django 5.1.5 on 2025-01-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
